name: Deploy Database Schema to Railway

on:
  push:
    branches:
      - prod  # Trigger workflow only on the 'prod' branch

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install Railway CLI
      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli

      # Deploy Project and Apply Schema
      - name: Deploy Database Schema
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          # Login to Railway
          railway login --token $RAILWAY_API_TOKEN

          # Deploy Project
          railway up --detach

          # Apply the schema to the PostgreSQL database
          railway run psql -U $PGUSER -h $PGHOST -d $PGDATABASE -p $PGPORT -f database/bundlwise_schema.sql