name: Deploy to Production

# Only trigger on push to main/prod branch
on:
  push:
    branches:
      - prod  # Sirf prod branch pe push hone par chalega

env:
  PROJECT_ID: bundlwise16           # Update project ID
  GAR_LOCATION: asia-south1      # Container registry location
  SERVICE: bundlwise-backend     # Service name for backend
  REGION: asia-south1           # Region

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/app:${{ github.sha }}" .
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/app:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE \
            --image "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE:${{ github.sha }}" \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated 