name: Prisma Studio
env:
  PROJECT_ID: bundlwise16

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'How long to keep studio running (in minutes)'
        required: true
        default: '30'

jobs:
  run-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Setup Cloud SQL Proxy
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Run Prisma Studio
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npx prisma studio &
          echo "Prisma Studio is running on http://localhost:5555"
          echo "This session will timeout in ${{ github.event.inputs.timeout }} minutes"
          sleep $(( ${{ github.event.inputs.timeout }} * 60 )) 